### PR TITLE
Add decorators for unified method patching/replacement

### PR DESCRIPTION
**Pull request by stphivos**
Provide the ability to patch a chain of methods of a Django model (or any class for that matter), and be able to verify that those were called with the expected parameters.

For example to be able to replace this:
```python
class TestCar(TestCase):
  qs = MockSet()

  @patch.object(Car, 'objects', qs)
  @patch.object(Car, 'validate_price')
  @patch.object(Car, 'save')
  def test_car_validates_price_before_save(self, save_mock, validate_price_mock):
    validate_price_mock.return_value = True

    obj = Car(price=80000, speed=300)
    obj.save()

    validate_price_mock.assert_called_with()
```

with this:
```python
class CarModelMocker(ModelMocker):
  """ If a model method passed in the test is provided it is bootstrapped
  with the implementation below otherwise it's replaced with a MagicMock """

  def validate_price(self):
    """ Skip expensive call to remote api """
    return True  # Or a more complex response

class TestCar(TestCase):
  @CarModelMocker(Car, 'validate_price', 'method_to_skip1', 'method_to_skip2...')
  def test_car_validates_price_before_save(self, mocker):
    obj = Car(price=80000, speed=300)
    obj.save()

    mocker.method('validate_price').assert_called_with()
```

### CODE REVIEW

**Comment by donkirkby** [comment]
That's an interesting idea, @stphivos, but can you help me understand how it's different from the features that the `mock` module already provides?

I think I see the scenario where you're trying to patch several features of a model class, but the example you gave doesn't look like it would actually work. Here's my attempt to write a small example that actually requires several patches. Let's imagine that we want to write a `Car.discount_slow()` method that applies a discount to all slow cars, and validates those discounted prices before saving them.

    class Car(models.Model):
        make = models.ForeignKey(Manufacturer)
        model = models.CharField(max_length=25, blank=True, null=True)
        speed = models.IntegerField()
        price = models.IntegerField()
    
        def format_speed(self):
            return '{0} km/h'.format(self.speed)
    
        def validate_price(self):
            # Call some expensive API, raise ValidationError
            pass
    
        def clean(self):
            super(Car, self).clean()
            self.validate_price()
    
        @classmethod
        def discount_slow(cls):
            for car in Car.objects.filter(speed__lt=100):
                car.price /= 2
                car.full_clean()
                car.save()

Here's my modified version of the test from your example:

    @patch.object(Car, 'clean_fields')
    @patch.object(Car, 'validate_price')
    @patch.object(Car, 'objects', new_callable=MockSet)
    @patch.object(Car, 'save')
    def test_car_validates_price_in_discount_slow(self,
                                                  save_mock,
                                                  objects_mock,
                                                  validate_price_mock,
                                                  clean_fields_mock):
        fast_price = 80000
        fast = Car(price=fast_price, speed=300)
        slow_price = 5000
        slow = Car(price=slow_price, speed=55)
        objects_mock.add(fast, slow)

        Car.discount_slow()

        self.assertEqual(fast_price, fast.price)  # no discount
        self.assertEqual(slow_price / 2, slow.price)
        save_mock.assert_called_once_with()
        clean_fields_mock.assert_called_once_with(exclude=[])
        validate_price_mock.assert_called_once_with()

We don't want the developer to need so many patches, right? The changes in pull request #28 will patch `objects` and `save`, along with any related models. They should also be compatible with other patches, you just have to apply `mocked_relations` on the outside, because it swallows the mocks it creates.

    @mocked_relations(Car)
    @patch.object(Car, 'clean_fields')
    @patch.object(Car, 'validate_price')
    def test_car_validates_price_in_discount_slow2(self,
                                                   validate_price_mock,
                                                   clean_fields_mock):
        fast_price = 80000
        fast = Car(price=fast_price, speed=300)
        slow_price = 5000
        slow = Car(price=slow_price, speed=55)
        Car.objects.add(fast, slow)

        Car.discount_slow()

        self.assertEqual(fast_price, fast.price)  # no discount
        self.assertEqual(slow_price / 2, slow.price)
        Car.save.assert_called_once_with()
        clean_fields_mock.assert_called_once_with(exclude=[])
        validate_price_mock.assert_called_once_with()

Another option is [`@patch.multiple()`][multi].

    @mocked_relations(Car)
    @patch.multiple(Car, clean_fields=DEFAULT, validate_price=DEFAULT)
    def test_car_validates_price_in_discount_slow3(self,
                                                   validate_price,
                                                   clean_fields):
        fast_price = 80000
        fast = Car(price=fast_price, speed=300)
        slow_price = 5000
        slow = Car(price=slow_price, speed=55)
        Car.objects.add(fast, slow)

        Car.discount_slow()

        self.assertEqual(fast_price, fast.price)  # no discount
        self.assertEqual(slow_price / 2, slow.price)
        Car.save.assert_called_once_with()
        clean_fields.assert_called_once_with(exclude=[])
        validate_price.assert_called_once_with()

Do these suggestions work as well as your changes for the scenario you were trying to improve? Did I understand the scenario?

[multi]: https://docs.python.org/3/library/unittest.mock.html#patch-multiple

**Comment by stphivos** [comment]
You are right it wouldn't work with a decorator as in my example because I had only added support for using as a context manager. I updated the PR to support both.

The difference with the built-in features of the mock module may not be very obvious with the simple example of `Car` and a `validate` method. My goal is to not simply suppress Django CRUD operations but to also have control over what gets called/returned while the tests remain readable and small to the point.

**Mocker**: Patches specified methods with provided subclass implementations (not necessarily model)
&nbsp;&nbsp;|_ **ModelMocker**:  Supplies Django CRUD methods to the above and wires to a MockSet
&nbsp;&nbsp;&nbsp;&nbsp;|_ **MyCustomModelMocker**: Adds support for custom methods
&nbsp;&nbsp;|_ **MyCustomServiceMocker**: Adds support for custom methods

I have included a more realistic non-trivial example below. Suppose I have a `Transaction` polymorphic model that is subclassed by concrete implementations that talk to their corresponding external systems throughout their lifecycle for things like `get_backend_state`, `get_customer_details` etc.

**models.py**
```python
class Transaction(PolymorphicModel):
    STATUS_APPROVED = 'approved'
    STATUS_PROCESSED = 'processed'
    STATUS_DECLINED = 'declined'

    STATUSES = (
        (0, STATUS_APPROVED),
        (1, STATUS_PROCESSED),
        (2, STATUS_DECLINED)
    )

    status = models.CharField(choices=STATUSES)
    user = models.ForeignKey(User)
    external_id = models.CharField()
    amount = models.DecimalField()
    created_date = models.DateTimeField()
    value_date = models.DateTimeField(null=True)

    def get_backend_state(self):  # abstract
        raise NotImplementedError()

    def get_customer_details(self):  # abstract
        raise NotImplementedError()

    def validate(self):  # abstract
        raise NotImplementedError()

    def save(self, *args, **kwargs):
        self.validate()
        self.user = User(**self.get_customer_details())

        super(Transaction, self).save(*args, **kwargs)

    def reconcile(self):  # abstract
        raise NotImplementedError()


class XProviderTransaction(Transaction):
    customer_id = models.CharField()
    source_ip = models.IPAddressField()

    def get_backend_state(self):
        transaction = xprovider_api.Transaction.retrieve(self.external_id)
        return transaction

    def get_customer_details(self):
        customer = xprovider_api.Customer.retrieve(self.customer_id)
        return dict(
            first_name=customer['firstName'],
            last_name=customer['lastName'],
            email=customer['email'],
        )

    def validate(self):
        backend_data = self.get_backend_state()
        if not backend_data:
            raise ValueError('Transaction does not exist')

        if backend_data['amount'] != self.amount:
            raise ValueError('Transaction amount is invalid')

    def reconcile(self):
        backend_data = self.get_backend_state()

        self.status = {
            'authorized': self.STATUS_APPROVED,
            'paid': self.STATUS_PROCESSED,
            'declined': self.STATUS_DECLINED
        }[backend_data['state']]

        self.value_date = backend_data['value_date']
        self.save()


class YProviderTransaction(Transaction):
    subscriber_id = models.IntegerField()

    """
    YProvider integration logic similar to XProvider shown above.
    """
```

**tests.py**
```python
class TestXProviderTransactions(TestCase):
    class XProviderBackend(ModelMocker):
        """
        This class simulates calls to the external backend and can be shared among tests.

        While it generates random complex responses based to the specs of the external api,
        we can also specify what we expect to be able to test multiple scenarios.

        Since it inherits from ModelMocker, we don't have to worry about MyModel.objects or MyModel.save
        and can access the automatically wired instance of MockSet using instance.qs
        """

        should_validate = True
        customer_details = None
        remote_state = None

        def get_customer_details(self):
            return self.customer_details or {'firstName': 'random', 'lastName': 'random', 'email': 'random'}

        def validate(self):
            if not self.should_validate:
                raise InvalidTransactionError()

        def get_backend_state(self):
            return self.remote_state or {'value_date': 'random', 'state': 'random'}

    @XProviderBackend(XProviderTransaction, 'get_customer_details', 'validate')
    def test_save_does_not_happen_when_transaction_invalid(self, backend):
        backend.should_validate = False

        t = XProviderTransaction()
        self.assertRaises(InvalidTransactionError, t.save)

        backend.method('validate').assert_called_with()
        backend.method('get_customer_details').assert_not_called()

    @XProviderBackend(XProviderTransaction, 'get_customer_details', 'validate')
    def test_save_validates_first(self, backend):
        t = XProviderTransaction()
        t.save()

        backend.method('validate').assert_called_with()
        backend.method('get_customer_details').assert_called_with()

    @XProviderBackend(XProviderTransaction, 'get_customer_details', 'validate')
    def test_save_updates_user_fk(self, backend):
        t = XProviderTransaction()
        t.save()

        self.assertEqual(t.user, User(**backend.get_customer_details()))

    @XProviderBackend(XProviderTransaction, 'get_backend_state')
    def test_reconcile_updates_processed_transaction(self, backend):
        backend.remote_state = {'value_date': 'random', 'state': 'paid'}

        t = XProviderTransaction()
        t.reconcile()

        self.assertEqual(t.value_date, backend.remote_state['value_date'])
        self.assertEqual(t.status, t.STATUS_PROCESSED)
```

**Comment by donkirkby** [comment]
Thanks for the explanation, @stphivos, I think we took different approaches to similar goals. I think your `Mocker` is similar to `mock.patch.multiple` or my `PatcherChain`, and your `ModelMocker` is similar to my `mocked_relations` patcher. Personally, I prefer my flexible building block approach that can be assembled into a chain of patchers, but you should take the approach you prefer. It's your project.

If you would like to use any of my code for mocking related models, feel free to cherry pick it into your `ModelMocker`.

Be careful with that `MockSet` in `ModelMocker.qs`, it may carry state from one test method to another.

Consider implementing the full patcher interface in `Mocker` (`start()` and `stop()`), it can be helpful when you want to access the mock objects in your `setUp()` methods.

**Comment by stphivos** [comment]
Hey @donkirkby, thanks for the feedback. I decided to merge both because I consider both `mocked_relations` and `ModelMocker` very useful.

The first focuses on model relationships and the second on general CRUD or other expensive calls that need to be easily patched with a complex response that needs to be calculated and shared across tests. It's true they have some overlapping code that needs to be refactored, but I would rather have them available now and get to that later down the line.

I will merge mine after we merge yours to deal with the conflicts.

**Comment by donkirkby** [comment]
OK, sounds good.

**Pull request merged**
