### PR TITLE
Adding overlap operator for ArrayFields

### PR DESCRIPTION
**Pull request by lvieirajr**
This PR adds the `__overlap` operator, which is available for ArrayFields on the django postgres integration.
https://docs.djangoproject.com/en/3.2/ref/contrib/postgres/fields/#overlap

### CODE REVIEW

**Review by gmorada — APPROVED** [review]

**Comment by lvieirajr** [comment]
Hey @stphivos has anyone been actively maintaining this repository?

**Comment by lvieirajr** [comment]
This needs a more intricate change to the `is_match` method.
Because of the way it is written it actually tries to evaluate all the lambdas, since it uses a variable name that just exists on the scope it lives in.
That won't work for some of the cases where you are looking at elements inside of a list, because another comparison will try to do a `<=` between an int and a list.

**Comment by lvieirajr** [comment]
These changes should be ready to be reviewed/merged.
The new comparison file was created and it should enable for very easy additions of new comparisons and even for upgrades on the ones that currently exist to support different data types.

**Comment by stphivos** [comment]
Looks great thanks!!

**Pull request merged**
