### PR TITLE
Add utils.mock_django_setup() to mock out all the Django configuration.

### PR DESCRIPTION
**Pull request by donkirkby**
Update example Django project to show how to run mock tests without a database.
Configure tox to execute Django tests and mock tests from the example project.

Do you have any thoughts on how to call `mock_django_setup()`? It has to be called *before* any of the model classes are defined, so I called it from the `mock_setup` module, and then import that before importing any models.

It feels messy to run stuff at import time, but I think Django is forcing us into it by running their own stuff at import time.

### CODE REVIEW

**Comment by stphivos** [comment]
Hey Don, thanks! I think it's a great idea to improve the speed of unit tests by avoiding use/creation of a database. I was wondering, what is the benefit of doing a mock django setup instead of including our own test runner in the project that might look like this:

**django_mock_queries/runners.py**
```python
from django.test.runner import DiscoverRunner


class NoDbTestRunner(DiscoverRunner):
    """ A test runner to test without database creation """

    def setup_databases(self, **kwargs):
        """ Override the database creation defined in parent class """
        pass

    def teardown_databases(self, old_config, **kwargs):
        """ Override the database teardown defined in parent class """
        pass

# TODO: Possibly provide some useful feedback like "Mock database tried to execute SQL..."?
```

so that devs who would like to benefit from this have to add/modify the following test settings with only 2 lines - at a single place for every project:

**myproject/unittest_settings.py**
```python
from settings import *

TEST_RUNNER = 'django_mock_queries.runners.NoDbTestRunner'
```

and run unit tests by supplying their custom settings:
```
python manage.py test myapp --settings=myproject.unittest_settings
```

I would like to shift the responsibility of setting up things to us instead of whoever uses the library so more people feel warmer towards unit testing :)

**Comment by donkirkby** [comment]
I just hadn't thought of replacing the test runner. :blush: I'll play around with that idea tomorrow. One thing that might allow would be to make all the regular Django tests just get skipped when you run against the mock database. Then I could use the `manage.py` script to run all tests or pure unit tests, and just change the settings file.

Off the top of my head, I'm worried that replacing the test runner would stop you from running your Django tests with other test runners like pytest, for example. I'll also look at replacing the database configuration with a mocked version. That might let you choose any test runner you like.

Either way, it might help us avoid some of the nasty stuff I had to do at import time to mock out the Django set up.

I completely agree that we want to make these tools as easy to use as possible. That's why I tried to make the example easier to find and easier to read. Running the example tests from tox will also make sure we don't break the example with changes to the code.

**Comment by donkirkby** [comment]
I added methods to `utils` to either mock out the Django database when running under the Django test runner, or to mock out the Django setup for running under regular `unittest` or `pytest`. I made the example project mock out the Django database, because it's easier.
The `django_mock_queries` tests continue to mock out the Django setup. It's very similar to what you currently do in `master`, I just added the mocked out database connection.

**Comment by stphivos** [comment]
Awesome thanks! I wanted to share a few thoughts to make it clearer for people to use:

* Moving `monkey_patch_test_db`, `mock_django_setup`, `mock_django_connection` from utils to a separate `mocks.py` module

* Renaming settings modules under examples/users/users `mock_setup` -> `settings_mock_setup`, `settings_mocked` -> `settings_mock_db` to follow an obvious naming convention

* When running tox I get the following error:
	ImportError: 'tests' module incorrectly imported from '/$HOME/Projects/django_mock_queries/examples/users/analytics/tests'. Expected '/$HOME/Projects/django_mock_queries/examples/users/analytics'. Is this module globally installed?

	Do you think it's necessary to be able to run the example tests from tox when building the library? In that case we could just call a script in the root of that project that knows how to run all its tests.

From a user's perspective we are providing the following new features - if i understood correctly:

* Mock django's setup in settings

```python
from django_mock_queries.utils import mock_django_setup

mock_django_setup('users.settings')
```

* Mock django's db connection in settings

```python
from django_mock_queries.utils import monkey_patch_test_db

from users.settings import *

monkey_patch_test_db()
```

Shall we explain in the "docs" how and when each one is more appropriate to use?

I can also add a simple skip db creation test runner with an example in users settings after we merge this PR. `Py.test` with `pytest-django` works well with that and it's good to have options!

**Comment by donkirkby** [comment]
Good suggestions, I'll work on them over the next few days. Here are some details and clarifying questions:

* Moving stuff from utils to a separate `mocks.py` module: will do.
* Renaming settings modules: I don't think this is needed. `mock_setup.py` was leftover from my original method, so I will just delete it. That leaves two files: `settings.py` that runs tests against the regular test database and `settings_mocked.py` that runs without a database.
* Errors running `tox`: I'm confused. Does running `tox --recreate` help? I don't see the error here, and Travis CI [isn't complaining][ci]. You don't have to run the example tests from tox, but I thought it was a good way to keep the example up to date and test your library with a real Django project. I was even thinking of trying to test against multiple versions of Django.
* New features to document:
  * Mock Django's db connection in settings. This is the only version I thought users needed to know about. It should be compatible with regular Django tests, and tests that need a real database need a `@skipIfDBFeature('is_mocked')` decorator. I haven't tested it with pytest-django, but I'm optimistic that it will work. I'll clarify the documentation in the README.
  * Mock Django setup during import. This is needed for pure unit tests that don't run under the Django test runner. For example, the tests for `django_mock_queries` itself. I was thinking of this as an internal feature, and I wasn't planning to document it other than in the source code. I thought it would be less confusing that way, but I'm happy to document it in the README if you wish.
  * Alternative test runner that skips DB creation. If the first feature works with pytest, is there a benefit to adding a test runner?

[ci]: https://travis-ci.org/stphivos/django-mock-queries/jobs/183452716#L218

**Comment by stphivos** [comment]
Thanks for the explanation!

* OK
* Sounds good
* The issue was that there was both a directory and a module file named `tests` and after deleted the leftover it went away!

About the docs, I think we are good with just the clarification for the first point and leave the second one out. I see your point maybe there's no real benefit to add a test runner, if needed we can add it in the future.

Also sorry for the list of commits mess, I amended the 3 commits I merged yesterday by `git rebase` that were accidentally using wrong author details. I resolved the conflicts now but hope I didn't cause any inconvenience!

**Comment by donkirkby** [comment]
Wow, that is a mess. Now you know why you're not supposed to rebase a public branch.

I'll try creating a new `mock-django-db` branch and cherrypicking my commits. If that goes smoothly, I'll create a new pull request with a link back here for the discussion.

**Comment by stphivos** [comment]
Yep, now I do!

That sounds ideal, fingers crossed and thank you for the effort!

**Pull request closed without merging**
