### PR TITLE
Bump django version lock

### PR DESCRIPTION
**Pull request by dmastylo**
Bump Django version lock to support newly released Django2.1

### CODE REVIEW

**Comment by stphivos** [comment]
Thanks!

**Comment by dmastylo** [comment]
@stphivos when do you think a release could be cut?

**Comment by stphivos** [comment]
Hey @dmastylo I will create a release in the next couple days and post an update here too.

**Comment by stphivos** [comment]
Released [v2.1.1](https://pypi.org/project/django_mock_queries/)

**Pull request merged**
