### PR TITLE
Fix utils get attribute for undefined/unset nested attributes

### PR DESCRIPTION
**Pull request by stphivos**

### CODE REVIEW

**Comment by donkirkby** [comment]
Sorry about taking so long to respond. I think I understand why you want to do this, but you haven't dealt with all the impacts of raising a new exception. I suggest you do the following:

1. Put my test back in from PR #16. (It failed when I tried to run it with the code from this branch.)
2. Look at all the other places where you call `get_attribute()` and add exception handlers.

Let me know if you'd like me to help with this.

In the exception handlers, you'll probably need to distinguish between [`ObjectDoesNotExist` exceptions][ex] and other `AttributeError` exceptions, because `ObjectDoesNotExist` exceptions should be used for filtering, where other `AttributeError` exceptions should be raised to the caller. (My test on the other pull request just uses a plain `AttributeError`, so it would need to be changed.)

Here's a snippet that shows two different attribute requests against a real database that will raise a `DoesNotExist` exception and a plain `AttributeError` exception. (I'm working on some features that will raise these two errors from a mocked model, but I'm not ready to create a pull request for them yet.)

[ex]: https://docs.djangoproject.com/en/1.10/ref/exceptions/#django.core.exceptions.ObjectDoesNotExist

    # Tested with Django 1.9.2
    import logging
    import sys
    
    import django
    from django.apps import apps
    from django.apps.config import AppConfig
    from django.conf import settings
    from django.core.exceptions import ObjectDoesNotExist
    from django.db import connections, models, DEFAULT_DB_ALIAS
    from django.db.models.base import ModelBase
    
    from mock import patch, PropertyMock, MagicMock
    
    NAME = 'udjango'
    
    
    def main():
    
        setup()
    
        class Person(models.Model):
            first_name = models.CharField(max_length=30)
            last_name = models.CharField(max_length=40)
    
        class Personality(models.Model):
            person = models.OneToOneField(Person, related_name="personality")
            description = models.CharField(max_length=1000)
    
            def __str__(self):
                return self.description
    
        syncdb(Person)
        syncdb(Personality)
    
        p1 = Person(first_name='Jimmy', last_name='Jones')
        p1.save()
        p2 = Person(first_name='Bob', last_name='Brown')
        p2.save()
        Personality.objects.create(person=p1, description='peppy')
    
        logging.info("Jimmy's personality is %s.", p1.personality.description)
        try:
            logging.info("Bob's personality is %s.", p2.personality.description)
        except Personality.DoesNotExist:
            logging.info("Bob has no personality.")
    
        try:
            logging.info("Bob's bogus field is %s.", p2.bogus_field)
        except AttributeError:
            logging.info("Bob has no bogus field.")
    
    
    def setup():
        DB_FILE = NAME + '.db'
        with open(DB_FILE, 'w'):
            pass  # wipe the database
        settings.configure(
            DEBUG=True,
            DATABASES={
                DEFAULT_DB_ALIAS: {
                    'ENGINE': 'django.db.backends.sqlite3',
                    'NAME': DB_FILE}},
            LOGGING={'version': 1,
                     'disable_existing_loggers': False,
                     'formatters': {
                        'debug': {
                            'format': '%(asctime)s[%(levelname)s]'
                                      '%(name)s.%(funcName)s(): %(message)s',
                            'datefmt': '%Y-%m-%d %H:%M:%S'}},
                     'handlers': {
                        'console': {
                            'level': 'DEBUG',
                            'class': 'logging.StreamHandler',
                            'formatter': 'debug'}},
                     'root': {
                        'handlers': ['console'],
                        'level': 'INFO'},
                     'loggers': {
                        "django.db": {"level": "DEBUG"}}})
        app_config = AppConfig(NAME, sys.modules['__main__'])
        apps.populate([app_config])
        django.setup()
        original_new_func = ModelBase.__new__
    
        @staticmethod
        def patched_new(cls, name, bases, attrs):
            if 'Meta' not in attrs:
                class Meta:
                    app_label = NAME
                attrs['Meta'] = Meta
            return original_new_func(cls, name, bases, attrs)
        ModelBase.__new__ = patched_new
    
    
    def syncdb(model):
        """ Standard syncdb expects models to be in reliable locations.
    
        Based on https://github.com/django/django/blob/1.9.3
        /django/core/management/commands/migrate.py#L285
        """
        connection = connections[DEFAULT_DB_ALIAS]
        with connection.schema_editor() as editor:
            editor.create_model(model)
    
    main()

**Comment by stphivos** [comment]
Hey, rough last few weeks! Thank you so much for the snippet and the detailed explanation. I agree this is not done correctly yet.

Looking at the usage of `get_attribute` is seems that `order_by` is directly using it and `filter` & `remove` are indirectly using it through the `matches` utility function.

It seems from django 1.10.3 source-code that some attribute-related errors are raised before and some after the `__iter__` method of the model `QuerySet` class.

But this happens for performance reasons since `QuerySet` supports quick chainning where expensive calls get evaluated once at the end. In the case of `MockSet` I like the idea how it's done since we're using memory collections and we can easily raise errors immediately.

So I would aim at raising the same type of error messages as django, even if it's not done lazily.

In your snippet you are testing accessing related fields on the model itself, but `MockSet` doesn't deal with such cases since you can add real models or mock models to it for a test, e.g.:

```python
class Person(models.Model):
	first_name = models.CharField(max_length=30)
   	last_name = models.CharField(max_length=40)

   	@staticmethod
   	def get_all_johns():
   		return Person.objects.filter(first_name__iexact='john')

def test_get_all_johns_returns_only_people_with_first_name_john(self):	
	qs = MockSet()

	with patch('myapp.models.Person.object', qs):
		p1 = Person(first_name='John', last_name='Smith')
		p2 = MagicMock(first_name='john', last_name='smith')

		qs.add(p1, p2)
		assert p1 in Person.get_all_johns()
		assert p2 in Person.get_all_johns()
```

I tried to extend the snippet with more tests to see what errors django raises and when - with respect to the `QuerySet` side of things:
```python
class TestDemo(TestCase):
    def test_django_model_queryset_errors(self):
        from django.core.exceptions import FieldError
        from django.db.models import Manager, QuerySet

        manager = Personality.objects
        assert isinstance(manager, Manager)

        queryset = manager.all()
        assert isinstance(queryset, QuerySet)

        # Django 1.10.3 considers this case as an invalid field lookup
        try:
            # TypeError: Related Field got invalid lookup: wrong
            # Traceback: filter -> _filter_or_exclude -> add_q -> _add_q -> build_filter -> get_lookup
            # https://github.com/django/django/blob/46b40274dd44921f72a59771ecb3d2b2c7b3aa0b/django/db/models/fields/related.py#L694
            queryset = queryset.filter(person__wrong='test')
        except TypeError as exc:
            assert 'Related Field got invalid lookup' in exc.message

        # Django 1.10.3 considers this case as an invalid field
        try:
            # FieldError: Cannot resolve keyword 'wrong' into field. Choices are: ...
            # Traceback: filter -> _filter_or_exclude -> add_q -> _add_q -> build_filter -> solve_lookup_type -> names_to_path
            # https://github.com/django/django/blob/46b40274dd44921f72a59771ecb3d2b2c7b3aa0b/django/db/models/sql/query.py#L1326
            queryset = queryset.filter(wrong='test')
        except FieldError as exc:
            assert 'Cannot resolve keyword' in exc.message

        # Django 1.10.3 considers this case as an invalid field lookup - but this time with a FieldError
        try:
            # FieldError: Related Field got invalid lookup: wrong
            # Traceback: filter -> _filter_or_exclude -> add_q -> _add_q -> build_filter -> solve_lookup_type -> names_to_path
            # https://github.com/django/django/blob/46b40274dd44921f72a59771ecb3d2b2c7b3aa0b/django/db/models/sql/query.py#L1326
            queryset = queryset.filter(person__wrong__iexact='test')
        except FieldError as exc:
            assert 'Related Field got invalid lookup' in exc.message

        # Django does not raise an error here. It does so after the next statement that will cause the generation of the sql query
        queryset = queryset.order_by('wrong')

        # This will trigger QuerySet __iter__ method and will execute the sql if generated successfully without errors
        try:
            # FieldError: Cannot resolve keyword 'wrong' into field. Choices are: ...
            # Traceback: __iter__ -> _fetch_all -> __iter__ -> execute_sql -> as_sql -> pre_sql_setup -> get_order_by -> ... -> names_to_path
            # https://github.com/django/django/blob/46b40274dd44921f72a59771ecb3d2b2c7b3aa0b/django/db/models/sql/query.py#L1326
            list(queryset)
        except FieldError as exc:
            assert 'Cannot resolve keyword' in exc.message
```

Finally, it seems that django decides if a field belongs to a model using `model._meta.fields`. This we can easily do. 

What I propose is that we either try to imitate the cases above which are definitely not all of them, or simply raise either a TypeError or a FieldError in `get_attribute` so that the caller knows they've used a wrong field period!

Any ideas? :-)

**Comment by donkirkby** [comment]
OK, here's a summary of the problems I think we're both trying to solve. Let me know if I missed any.

1. Raise an error when there's a typo in a queryset's field name.
2. Use one-to-one or many-to-one relations as a queryset filter, particularly `_isnull`.
3. Raise realistic errors in other scenarios, like `MyModel.DoesNotExist`.

I like your idea of raising a `FieldError` when a field name is not in `_meta.fields`. Perhaps that check alone is enough, and `get_attribute` could just return `None` for any other attribute. I'm going to write a new pull request with those two changes to solve goals 1 and 2, then I'll propose another pull request for number 3.

**Comment by stphivos** [comment]
Thanks!

1 & 2: Sounds good
3: I think we do that already for `MockSet`.`get/latest/earliest` that replace their equivalent methods of Django's `QuerySet`. Anything I might have missed?

**Pull request closed without merging**
