### PR TITLE
Replace model-mommy with model-bakery

### PR DESCRIPTION
**Pull request by mazulo**
Model Mommy is no longer maintained and was replaced by Model Bakery.

### CODE REVIEW

**Comment by mazulo** [comment]
@stphivos CI failure seems unrelated with the changes here but I might be missing something. Please let me know and I will fix it.

**Comment by stphivos** [comment]
Thanks @mazulo ! [.travis.yml](https://github.com/stphivos/django-mock-queries/blob/cf2559182b82712908a4e0dd270661e287f7f04b/.travis.yml#L58) `tox>=1.9` [installed](https://api.travis-ci.org/v3/job/638525825/log.txt) `tox-3.14.3` which seems to be incompatible. That used to be `tox==2.1.1` based on `requirements/dev.txt` but that isn't used for Travis, just the local dev env. So maybe it needs to be pinned in `travis.yml` also?

**Comment by mazulo** [comment]
Ooh, I see. Yeah it makes sense. I'll update and give it a shot!

**Comment by mazulo** [comment]
@stphivos it seems Travis is really mad at me 😂I'll try to dig deeper on it later today. But here you can see that locally everything is working great: https://gist.github.com/mazulo/a5687b3267b75351914b3f1810ea5058

**Comment by stphivos** [comment]
Hi @mazulo, apologies for the delay. It seems its the package owners which are mad at us for dropping support for python 2.7. I know some people still use it so I tried to find a fix. I pinned `zipp==0.4` which is an indirect dependency from pytest. But I had to drop support for python `3.4` which isn't too much work to migrate to a newer version.

Closing this PR since your commits are already part of PR #108.

**Pull request closed without merging**
